routes/web.php
<?php

use App\Http\Controllers\Admin\AdminSettingController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\FAQController;
use App\Http\Controllers\Admin\InstructorController;
use App\Http\Controllers\Admin\LanguageController;
use App\Http\Controllers\Admin\LicenseController;
use App\Http\Controllers\Admin\NotiTemplateController;
use App\Http\Controllers\Admin\PayoutController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\ReportController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\StudentController;
use App\Http\Controllers\Admin\SubCategoryController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Admin\WebLanguageController;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\Auth\VerificationController;
use App\Http\Controllers\ChatGroupController;
use App\Http\Controllers\FeedbackController;
use App\Http\Controllers\Instructor\AuthController;
use App\Http\Controllers\Instructor\BusinessController;
use App\Http\Controllers\Instructor\CourseContentController;
use App\Http\Controllers\Instructor\CourseController;
use App\Http\Controllers\Instructor\InsVerifyController;
use App\Http\Controllers\Instructor\LectureController;
use App\Http\Controllers\Instructor\LiveStreamController;
use App\Http\Controllers\Instructor\SpecialDiscountController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\SocialController;
use App\Http\Controllers\Student\CartController;
use App\Http\Controllers\Student\CourseRatingController;
use App\Http\Controllers\Student\IndexController;
use App\Http\Controllers\Student\InstructorDiscussionController;
use App\Http\Controllers\Student\LikeDislikeCourseController;
use App\Http\Controllers\Student\ReportAbuseController;
use App\Http\Controllers\Student\SavedCoursesController;
use App\Http\Controllers\Student\SubscriptionController;
use App\Models\Instructor;
use App\Models\Student;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::post('saveEnvData', [LicenseController::class, 'saveEnvData']);
Route::any('installer', [LicenseController::class, 'installer']);
Route::post('saveAdminData', [LicenseController::class, 'saveAdminData']);
Route::post('activeLicence', [LicenseController::class, 'activeLicence']);
Route::get('activeLicence', [LicenseController::class, 'activeLicenceGet']);
Route::get('locale/{locale}', function ($locale) {
    \Session::put('locale', $locale);
    return redirect()->back();
})->name('locale.change');
Route::get('/home', function () {
    return redirect('admin/dashboard');
})->name('home');

Route::get('category/{id}', [CategoryController::class, 'getCategory']);
Route::group(['prefix' => 'admin'], function () {
    Route::get('/', function () {
        return redirect('admin/dashboard');
    });

    Route::group(['middleware' => ['auth', 'web']], function () {
        Route::get('/dashboard', [AdminSettingController::class, 'dashboard']);
        Route::resources([
            'role' => RoleController::class,
            'users' => UsersController::class,
            'languages' => LanguageController::class,
            'categories' => CategoryController::class,
            'sub-categories' => SubCategoryController::class,
            'instructors' => InstructorController::class,
            'students' => StudentController::class,
            'faqs' => FAQController::class,
            'payout' => PayoutController::class,
            'noti-template' => NotiTemplateController::class,
            'web-language' => WebLanguageController::class,
        ]);
        Route::get('download/{lang?}', [WebLanguageController::class, 'downloadBaseFile'])->name('download.langFile');
        Route::group(['prefix' => 'setting'], function () {
            Route::get('legal', [AdminSettingController::class, 'legal'])->name('setting.legal');
            Route::get('general', [AdminSettingController::class, 'general'])->name('setting.general');
            Route::get('mail', [AdminSettingController::class, 'email'])->name('setting.mail');
            Route::get('social', [AdminSettingController::class, 'social'])->name('setting.social');
            Route::get('social-login', [AdminSettingController::class, 'sociallogin'])->name('setting.social-login');
            Route::get('seo', [AdminSettingController::class, 'seo'])->name('setting.seo');
            Route::get('appearance', [AdminSettingController::class, 'appearance'])->name('setting.appearance');
            Route::get('payment', [AdminSettingController::class, 'payment'])->name('setting.payment');
            Route::get('other', [AdminSettingController::class, 'other'])->name('setting.other');
            Route::post('update', [AdminSettingController::class, 'update'])->name('setting.update');
        });
        Route::group(['prefix' => 'report'], function () {
            Route::any('student-registration', [ReportController::class, 'studentReg'])->name('report.stureg');
            Route::any('instructor-registration', [ReportController::class, 'instructorReg'])->name('report.instructorreg');
            Route::any('subscription', [ReportController::class, 'subscription'])->name('report.subscription');
            Route::any('course-sell', [ReportController::class, 'courseSell'])->name('report.coursesell');
            Route::any('earning', [ReportController::class, 'earning'])->name('report.earning');
        });
        Route::get('verification', [InsVerifyController::class, 'index'])->name('verification.adindex');
        Route::get('feedback', [FeedbackController::class, 'index'])->name('feedback.index');
        Route::put('verification/{id}', [InsVerifyController::class, 'update'])->name('verification.update');

        Route::get('profile', [ProfileController::class, 'edit'])->name('profile.adedit');
        Route::get('courses/{status}', [InstructorController::class, 'courseIndex']);
        Route::get('courses/{id}/show', [InstructorController::class, 'courseShow'])->name('admin-course.show');
        Route::get('review/{id}/delete', [InstructorController::class, 'reviewDelete'])->name('admin-review.delete');
        Route::post('courses/{id}/update', [InstructorController::class, 'courseUpdate'])->name('admin-course.update');
        Route::put('profile', [ProfileController::class, 'update'])->name('profile.adupdate');
        Route::put('profile/password', [ProfileController::class, 'password'])->name('profile.adpassword');
        Route::get('logout', function () {
            Auth::logout();
            return redirect('login');
        })->name('admin.logout');
    });
    Auth::routes(['verify' => true]);
    Route::get('/reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('admin.showResetForm');
    Route::get('/resetemail/{user_type}', [ForgotPasswordController::class, 'showLinkRequestForm'])->name('admin.showResetEmailForm');
    Route::post('/reset', [ResetPasswordController::class, 'reset'])->name('admin.password.update');
});

Route::group(['prefix' => 'instructor'], function () {
    Route::get('/', function () {
        return redirect('instructor/home');
    });

    Route::get('/email/verify', function () {

        if (Auth::user()->hasVerifiedEmail()) {
            return redirect('home');
        }
        return view('auth.verify');
    })->middleware('auth:instructor')->name('insverification.notice');

    Route::post('/email/verify/resend', function () {

        Auth::user()->sendEmailVerificationNotification();

        return back()->withResent(__('A fresh verification link has been sent to your email address..'));
    })->middleware(['auth:instructor', 'web'])->name('insverification.resend');
    Route::get('email/verify/{id}/{hash}/{user_type}', [VerificationController::class, 'verify'])->name('ownverification.verify');

    Route::get('register', [AuthController::class, 'registerView']);
    Route::get('{user_type?}/auth/{provider}/redirect', [SocialController::class, 'redirectToProvider']);
    Route::get('login', [AuthController::class, 'LoginView']);
    Route::get('/reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('instructor.showResetForm');
    Route::get('/resetemail/{user_type}', [ForgotPasswordController::class, 'showLinkRequestForm'])->name('instructor.showResetEmailForm');
    Route::post('/reset', [ResetPasswordController::class, 'reset'])->name('instructor.password.update');
    Route::post('register', [AuthController::class, 'register']);
    Route::post('login', [AuthController::class, 'login']);
    Route::group(['middleware' => ['auth:instructor', 'verified:insverification.notice']], function () {
        Route::resources([
            'courses' => CourseController::class,
            'course-content' => CourseContentController::class,
            'special-discount' => SpecialDiscountController::class,
            'lectures' => LectureController::class,
            'live-stream' => LiveStreamController::class,
        ]);

        Route::get('messages/{id}', [ChatGroupController::class, 'show'])->name('ins-message.show');
        Route::post('messages/send', [ChatGroupController::class, 'savemsg'])->name('ins-message.send');
        Route::post('messages/ajax', [ChatGroupController::class, 'latestmsgajax'])->name('ins-message.ajax');
        Route::get('messages', [ChatGroupController::class, 'index'])->name('ins-messages');

resources/views/inc/footer.blade.php
<footer class="main-footer">
    <div class="footer-left">
        {{__('Copyright')}} &copy; {{date('Y')}} <div class="bullet"></div> {{__('Design By')}} <a href="">Team</a>
    </div>
    <div class="footer-right">
        1.0.2
    </div>
</footer>

resources/views/inc/navbar.blade.php
<aside id="sidebar-wrapper">
    <div class="sidebar-brand">
        <a href="{{url('admin/dashboard')}}">{{env("APP_NAME")}}</a>
    </div>
    <div class="sidebar-brand sidebar-brand-sm">
        <a href="{{url('admin/dashboard')}}"></a>
    </div>
    <ul class="sidebar-menu">

        <li class="{{ request()->is('admin/dashboard') ? 'active' : '' }}"><a class="nav-link"
                href="{{ url('admin/dashboard') }}"><i class="fas fa-tachometer-alt"></i>
                <span>{{__('Dashboard')}}</span></a>
        </li>

        <li class="menu-header">{{__('Starter')}}</li>

        @can('role_access')
        <li class="{{ request()->is('admin/role') ? 'active' : '' }}"><a class="nav-link"
                href="{{ route('role.index') }}"><i class="far fa-address-book"></i> <span>{{__('Role')}}</span></a>
        </li>
        @endcan

        @can('user_access')
        <li class="{{ request()->is('admin/users') ? 'active' : '' }}"><a class="nav-link"
                href="{{ route('users.index') }}"><i class="far fa-user"></i> <span>{{__('Users')}}</span></a>
        </li>
        @endcan

        @can('language_access')
        <li class="{{ request()->is('admin/languages') ? 'active' : '' }}"><a class="nav-link"
                href="{{ route('languages.index') }}"><i class="fas fa-language"></i>
                <span>{{__('Languages')}}</span></a></li>
        @endcan

        @can('category_access')
        <li class="{{ request()->is('admin/categories') ? 'active' : '' }}"><a class="nav-link"
                href="{{ route('categories.index') }}"><i class="fas fa-list-ul"></i>
                <span>{{__('Categories')}}</span></a></li>
        @endcan

        @can('sub_category_access')
        <li class="{{ request()->is('admin/sub-categories') ? 'active' : '' }}"><a class="nav-link"
                href="{{ route('sub-categories.index') }}"><i class="fas fa-boxes"></i>
                <span>{{__('Sub Categories')}}</span></a>
        </li>
        @endcan
        <li class="menu-header">{{__('Students')}}</li>

        @can('student_access')
        <li class="{{ request()->is('admin/students*') ? 'active' : '' }}"><a class="nav-link"
                href="{{ route('students.index') }}"><i class="fas fa-user"></i>
                <span>{{__('Student')}}</span></a>
        </li>
        @endcan
        <li class="menu-header">{{__('Instructor')}}</li>

        @can('instructor_access')
        <li class="{{ request()->is('admin/instructors*') ? 'active' : '' }}"><a class="nav-link"
                href="{{ route('instructors.index') }}"><i class="fas fa-chalkboard-teacher"></i>
                <span>{{__('Instructor')}}</span></a>
        </li>
        @endcan

        @can('verification_access')
        <li class="{{ request()->is('admin/verification*') ? 'active' : '' }}"><a class="nav-link"
                href="{{ route('verification.adindex') }}"><i class="fas fa-certificate"></i>
                <span>{{__('Verification')}}</span></a>
        </li>
        @endcan

        @can('payout_access')
        <li class="{{ request()->is('admin/payout*') ? 'active' : '' }}"><a class="nav-link"
                href="{{ route('payout.index') }}"><i class="fas fa-hand-holding-usd"></i>
                <span>{{__('Payout')}}</span></a>
        </li>
        @endcan
        @can('course_access')
        <li class="nav-item dropdown {{ request()->is('admin/courses/*') ? 'active' : '' }}">
            <a href="#" class="nav-link has-dropdown" data-toggle="dropdown"><i class="fas fa-book"></i>
                <span>{{__('Course')}}</span></a>
            <ul class="dropdown-menu">
                <li><a class="nav-link  {{ request()->is('admin/courses/pending') ? 'active' : '' }}"
                        href="{{ url('admin/courses/pending') }}">{{__('Waiting for approval')}}</a>
                </li>
                <li><a class="nav-link  {{ request()->is('admin/courses/all') ? 'active' : '' }}"
                        href="{{ url('admin/courses/all') }}">{{__('All')}}</a></li>
                <li><a class="nav-link  {{ request()->is('admin/courses/rejected') ? 'active' : '' }}"
                        href="{{ url('admin/courses/rejected') }}">{{__('Rejected')}}</a></li>
            </ul>
        </li>
        @endcan
        <li class="menu-header">{{__('Extra')}}</li>

        @can('setting_access')
        <li class="nav-item dropdown {{ request()->is('admin/setting/*') ? 'active' : '' }}">
            <a href="#" class="nav-link has-dropdown" data-toggle="dropdown"><i class="fas fa-cog"></i>
                <span>{{__('Settings')}}</span></a>
            <ul class="dropdown-menu">
                <li><a class="nav-link" href="{{ route('setting.general') }}">{{__('General')}}</a>
                </li>
                <li><a class="nav-link" href="{{ route('setting.legal') }}">{{__('Legal')}}</a>
                </li>
                <li><a class="nav-link" href="{{ route('setting.social') }}">{{__('Social')}}</a>
                </li>
                <li><a class="nav-link" href="{{ route('setting.payment') }}">{{__('Payment')}}</a>
                </li>
                <li><a class="nav-link" href="{{ route('setting.seo') }}">{{__('SEO')}}</a>
                </li>
                <li><a class="nav-link" href="{{ route('setting.mail') }}">{{__('Mail')}}</a>
                </li>
                <li><a class="nav-link" href="{{ route('setting.appearance') }}">{{__('Appearance')}}</a>
                </li>
                <li><a class="nav-link" href="{{ route('setting.other') }}">{{__('Other')}}</a>
                </li>

            </ul>
        </li>
        @endcan
        @can('report_access')
        <li class="nav-item dropdown {{ request()->is('admin/report/*') ? 'active' : '' }}">
            <a href="#" class="nav-link has-dropdown" data-toggle="dropdown"><i class="far fa-file-word"></i>
                <span>{{__('Reports')}}</span></a>
            <ul class="dropdown-menu">
                <li><a class="nav-link" href="{{ route('report.earning') }}">{{__('Earning')}}</a>
                </li>
                <li>
                    <a class="nav-link" href="{{ route('report.coursesell') }}">{{__('Cource Selling')}}
                    </a>
                </li>
                <li>
                    <a class="nav-link" href="{{ route('report.subscription') }}">{{__('Subscription')}}
                    </a>
                </li>
                <li>
                    <a class="nav-link" href="{{ route('report.instructorreg') }}">{{__('Instructor Registration ')}}
                    </a>
                </li>
                <li>
                    <a class="nav-link" href="{{ route('report.stureg') }}">{{__('Student Registration')}}
                    </a>
                </li>

            </ul>
        </li>
        @endcan

        @can('feedback_access')
        <li class="{{ request()->is('admin/feedback') ? 'active' : '' }}"><a class="nav-link"
                href="{{ route('feedback.index') }}"><i class="fas fa-comment"></i>
                <span>{{__('Feedback')}}</span></a>
        </li>
        @endcan

        @can('notification_access')
        <li class="{{ request()->is('admin/noti-template') ? 'active' : '' }}"><a class="nav-link"
                href="{{ route('noti-template.index') }}"><i class="fas fa-bell"></i>
                <span>{{__('Notification Template')}}</span></a>
        </li>
        @endcan
        @can('lang_access')
        <li class="{{ request()->is('admin/web-language') ? 'active' : '' }}"><a class="nav-link"
                href="{{ route('web-language.index') }}"><i class="fa fa-language"></i>
                <span>{{__('Web Languages')}}</span></a>
        </li>
        @endcan

        @can('faq_access')
        <li class="{{ request()->is('admin/faqs') ? 'active' : '' }}"><a class="nav-link"
                href="{{ route('faqs.index') }}"><i class="fas fa-question"></i>
                <span>{{__('FAQ')}}</span></a>
        </li>
        @endcan
    </ul>

</aside>

resources/views/inc/scripts.blade.php
<script src="{{ asset('frontend/js/jquery.min.js') }}"></script>
<script src="{{ asset('admin/assets/js/popper.min.js')}}">
</script>
<script src="{{ asset('frontend/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('admin/assets/js/nicescroll.min.js')}}"></script>
<script src="{{ asset('admin/assets/js/moment.min.js')}}"></script>

<script src="{{ asset('admin/assets/plugins/table/datatable/datatables.js')}}"></script>
<script src="{{ asset('admin/assets/plugins/table/datatable/button-ext/dataTables.buttons.min.js')}}"></script>
<script src="{{ asset('admin/assets/plugins/table/datatable/button-ext/jszip.min.js')}}"></script>
<script src="{{ asset('admin/assets/plugins/table/datatable/button-ext/buttons.html5.min.js')}}"></script>
<script src="{{ asset('admin/assets/plugins/table/datatable/button-ext/buttons.print.min.js')}}"></script>
<script src="{{ asset('admin/assets/js/stisla.js') }}"></script>
<script src="{{ asset('admin/assets/plugins/select2/select2.min.js')}}"></script>
<script src="{{ asset('admin/assets/js/scripts.js') }}"></script>
<script src="{{ asset('admin/assets/js/custom.js') }}"></script>
<script src="{{ asset('admin/assets/js/chart.js') }}"></script>
<link href="{{ asset('admin/assets/js/summernote.min.css') }}" rel="stylesheet">
<script src="{{ asset('admin/assets/js/summernote.min.js') }}"></script>

resources/views/inc/styles.blade.php
<link href="{{ asset('frontend/vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ asset('frontend/css/font-awesome.min.css')}}" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{{ asset('admin/assets/plugins/table/datatable/datatables.css')}}">
<link rel="stylesheet" type="text/css" href="{{ asset('admin/assets/plugins/table/datatable/custom_dt_html5.css')}}">
<link rel="stylesheet" type="text/css" href="{{ asset('admin/assets/plugins/table/datatable/dt-global_style.css')}}">

<link rel="stylesheet" type="text/css" href="{{ asset('admin/assets/plugins/select2/select2.min.css')}}">

<link rel="stylesheet" href="{{ asset('admin/assets/css/style.css') }}">
<link rel="stylesheet" href="{{ asset('admin/assets/css/components.css') }}">

resources/views/inc/topnav.blade.php
<form class="form-inline mr-auto">
    <ul class="navbar-nav mr-3">
        <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>

    </ul>

</form>
<ul class="navbar-nav navbar-right">
    <li class="dropdown dropdown-list-toggle"><a href="#" data-toggle="dropdown"
            class="nav-link nav-link-lg message-toggle beep"><i class="fa fa-language"></i></a>
        <div class="dropdown-menu dropdown-list dropdown-menu-right">
            <div class="dropdown-header">Languages

            </div>
            <div class="dropdown-list-content dropdown-list-message">
                <a href="{{ route('locale.change',['locale' => 'en']) }}" class="dropdown-item">
                    <div class="dropdown-item-desc">
                        <b>English</b>
                    </div>
                </a>
                @foreach ($weblang as $webl)
                <a href="{{ route('locale.change',['locale' => $webl->short_name]) }}" class="dropdown-item">
                    <div class="dropdown-item-desc">
                        <b>{{$webl->name}}</b>
                    </div>
                </a>
                @endforeach
            </div>

        </div>
    </li>
    <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
            <img alt="image" src="{{ asset(Auth::guard('web')->user()->image) }}" class="rounded-circle mr-1">
            <div class="d-sm-none d-lg-inline-block">Hi, {{Auth::guard('web')->user()->name ?? "No Login"}}</div>
        </a>
        <div class="dropdown-menu dropdown-menu-right">
            <div class="dropdown-title">Logged in </div>
            <a href="{{ route('profile.adedit') }}" class="dropdown-item has-icon">
                <i class="far fa-user"></i> {{__('Profile')}}
            </a>

            <a href="{{ route('setting.general') }}" class="dropdown-item has-icon">
                <i class="fas fa-cog"></i> {{__('Settings')}}
            </a>
            <div class="dropdown-divider"></div>
            <a href="{{ route('admin.logout') }}" class="dropdown-item has-icon text-danger">
                <i class="fas fa-sign-out-alt"></i> {{__('Logout')}}
            </a>
        </div>
    </li>
</ul>